<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBOOwSEF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBOOwSEF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBOOwSEF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBOOwSEF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBOOwSEF\App_KernelDevDebugContainer([
    'container.build_hash' => 'BOOwSEF',
    'container.build_id' => '2a658d9b',
    'container.build_time' => 1775510750,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBOOwSEF');
