services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    image: 'gotenberg/gotenberg:8'
    ports:
      - "3000:3000"   # ✅ IMPORTANT !!!
###< sensiolabs/gotenberg-bundle ###

###> rekalogika/gotenberg-pdf-bundle ###
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7
###< rekalogika/gotenberg-pdf-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###