<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NjvtsJ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NjvtsJ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'threadService' => ['privates', 'App\\Service\\ThreadService', 'getThreadServiceService', true],
            'uploadService' => ['privates', 'App\\Service\\ImageUploadService', 'getImageUploadServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'threadService' => 'App\\Service\\ThreadService',
            'uploadService' => 'App\\Service\\ImageUploadService',
        ]);

        if (isset($container->privates['.service_locator.NjvtsJ6'])) {
            return $container->privates['.service_locator.NjvtsJ6'];
        }

        return $container->privates['.service_locator.NjvtsJ6'] = $instance;
    }
}
