<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_21wACghService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.21wACgh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.21wACgh.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.21wACgh": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'categoryService' => ['privates', 'App\\Service\\CategoryService', 'getCategoryServiceService', true],
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
        ], [
            'category' => 'App\\Entity\\Category',
            'categoryService' => 'App\\Service\\CategoryService',
            'currentUserService' => 'App\\Service\\CurrentUserService',
        ]);

        if (isset($container->privates['.service_locator.21wACgh'])) {
            return $container->privates['.service_locator.21wACgh'];
        }

        return $container->privates['.service_locator.21wACgh'] = $instance;
    }
}
