<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_75u_TDwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75u.tDw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::deleteCategory' => ['privates', '.service_locator.21wACgh', 'get_ServiceLocator_21wACghService', true],
            'App\\Controller\\AdminController::editCategory' => ['privates', '.service_locator.21wACgh', 'get_ServiceLocator_21wACghService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.L13ndS.', 'get_ServiceLocator_L13ndS_Service', true],
            'App\\Controller\\AdminController::newCategory' => ['privates', '.service_locator.blzPcKd', 'get_ServiceLocator_BlzPcKdService', true],
            'App\\Controller\\AdminController::statistics' => ['privates', '.service_locator.cIzG9cr', 'get_ServiceLocator_CIzG9crService', true],
            'App\\Controller\\ForumController::archived' => ['privates', '.service_locator.WtSXxyl', 'get_ServiceLocator_WtSXxylService', true],
            'App\\Controller\\ForumController::deleteReply' => ['privates', '.service_locator.HdzICK7', 'get_ServiceLocator_HdzICK7Service', true],
            'App\\Controller\\ForumController::detail' => ['privates', '.service_locator.vBJCjPQ', 'get_ServiceLocator_VBJCjPQService', true],
            'App\\Controller\\ForumController::editReply' => ['privates', '.service_locator.HdzICK7', 'get_ServiceLocator_HdzICK7Service', true],
            'App\\Controller\\ForumController::feed' => ['privates', '.service_locator.CehbjXJ', 'get_ServiceLocator_CehbjXJService', true],
            'App\\Controller\\ForumController::followed' => ['privates', '.service_locator.G8PCkaG', 'get_ServiceLocator_G8PCkaGService', true],
            'App\\Controller\\ForumController::myThreads' => ['privates', '.service_locator.iY6bqSe', 'get_ServiceLocator_IY6bqSeService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.zVXiQ7C', 'get_ServiceLocator_ZVXiQ7CService', true],
            'App\\Controller\\NotificationController::delete' => ['privates', '.service_locator.iQcy2pB', 'get_ServiceLocator_IQcy2pBService', true],
            'App\\Controller\\NotificationController::index' => ['privates', '.service_locator.tszPrR6', 'get_ServiceLocator_TszPrR6Service', true],
            'App\\Controller\\NotificationController::open' => ['privates', '.service_locator.H6O0oHA', 'get_ServiceLocator_H6O0oHAService', true],
            'App\\Controller\\NotificationController::seen' => ['privates', '.service_locator.H6O0oHA', 'get_ServiceLocator_H6O0oHAService', true],
            'App\\Controller\\NotificationController::seenAll' => ['privates', '.service_locator.SokdwQV', 'get_ServiceLocator_SokdwQVService', true],
            'App\\Controller\\NotificationController::widget' => ['privates', '.service_locator.tszPrR6', 'get_ServiceLocator_TszPrR6Service', true],
            'App\\Controller\\ThreadManageController::delete' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController::downvote' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'App\\Controller\\ThreadManageController::edit' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController::follow' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'App\\Controller\\ThreadManageController::new' => ['privates', '.service_locator.NjvtsJ6', 'get_ServiceLocator_NjvtsJ6Service', true],
            'App\\Controller\\ThreadManageController::pin' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController::status' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController::upvote' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:deleteCategory' => ['privates', '.service_locator.21wACgh', 'get_ServiceLocator_21wACghService', true],
            'App\\Controller\\AdminController:editCategory' => ['privates', '.service_locator.21wACgh', 'get_ServiceLocator_21wACghService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.L13ndS.', 'get_ServiceLocator_L13ndS_Service', true],
            'App\\Controller\\AdminController:newCategory' => ['privates', '.service_locator.blzPcKd', 'get_ServiceLocator_BlzPcKdService', true],
            'App\\Controller\\AdminController:statistics' => ['privates', '.service_locator.cIzG9cr', 'get_ServiceLocator_CIzG9crService', true],
            'App\\Controller\\ForumController:archived' => ['privates', '.service_locator.WtSXxyl', 'get_ServiceLocator_WtSXxylService', true],
            'App\\Controller\\ForumController:deleteReply' => ['privates', '.service_locator.HdzICK7', 'get_ServiceLocator_HdzICK7Service', true],
            'App\\Controller\\ForumController:detail' => ['privates', '.service_locator.vBJCjPQ', 'get_ServiceLocator_VBJCjPQService', true],
            'App\\Controller\\ForumController:editReply' => ['privates', '.service_locator.HdzICK7', 'get_ServiceLocator_HdzICK7Service', true],
            'App\\Controller\\ForumController:feed' => ['privates', '.service_locator.CehbjXJ', 'get_ServiceLocator_CehbjXJService', true],
            'App\\Controller\\ForumController:followed' => ['privates', '.service_locator.G8PCkaG', 'get_ServiceLocator_G8PCkaGService', true],
            'App\\Controller\\ForumController:myThreads' => ['privates', '.service_locator.iY6bqSe', 'get_ServiceLocator_IY6bqSeService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.zVXiQ7C', 'get_ServiceLocator_ZVXiQ7CService', true],
            'App\\Controller\\NotificationController:delete' => ['privates', '.service_locator.iQcy2pB', 'get_ServiceLocator_IQcy2pBService', true],
            'App\\Controller\\NotificationController:index' => ['privates', '.service_locator.tszPrR6', 'get_ServiceLocator_TszPrR6Service', true],
            'App\\Controller\\NotificationController:open' => ['privates', '.service_locator.H6O0oHA', 'get_ServiceLocator_H6O0oHAService', true],
            'App\\Controller\\NotificationController:seen' => ['privates', '.service_locator.H6O0oHA', 'get_ServiceLocator_H6O0oHAService', true],
            'App\\Controller\\NotificationController:seenAll' => ['privates', '.service_locator.SokdwQV', 'get_ServiceLocator_SokdwQVService', true],
            'App\\Controller\\NotificationController:widget' => ['privates', '.service_locator.tszPrR6', 'get_ServiceLocator_TszPrR6Service', true],
            'App\\Controller\\ThreadManageController:delete' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController:downvote' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'App\\Controller\\ThreadManageController:edit' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController:follow' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'App\\Controller\\ThreadManageController:new' => ['privates', '.service_locator.NjvtsJ6', 'get_ServiceLocator_NjvtsJ6Service', true],
            'App\\Controller\\ThreadManageController:pin' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController:status' => ['privates', '.service_locator.MvDhjVE', 'get_ServiceLocator_MvDhjVEService', true],
            'App\\Controller\\ThreadManageController:upvote' => ['privates', '.service_locator.7vo.mx5', 'get_ServiceLocator_7vo_Mx5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::deleteCategory' => '?',
            'App\\Controller\\AdminController::editCategory' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::newCategory' => '?',
            'App\\Controller\\AdminController::statistics' => '?',
            'App\\Controller\\ForumController::archived' => '?',
            'App\\Controller\\ForumController::deleteReply' => '?',
            'App\\Controller\\ForumController::detail' => '?',
            'App\\Controller\\ForumController::editReply' => '?',
            'App\\Controller\\ForumController::feed' => '?',
            'App\\Controller\\ForumController::followed' => '?',
            'App\\Controller\\ForumController::myThreads' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\NotificationController::delete' => '?',
            'App\\Controller\\NotificationController::index' => '?',
            'App\\Controller\\NotificationController::open' => '?',
            'App\\Controller\\NotificationController::seen' => '?',
            'App\\Controller\\NotificationController::seenAll' => '?',
            'App\\Controller\\NotificationController::widget' => '?',
            'App\\Controller\\ThreadManageController::delete' => '?',
            'App\\Controller\\ThreadManageController::downvote' => '?',
            'App\\Controller\\ThreadManageController::edit' => '?',
            'App\\Controller\\ThreadManageController::follow' => '?',
            'App\\Controller\\ThreadManageController::new' => '?',
            'App\\Controller\\ThreadManageController::pin' => '?',
            'App\\Controller\\ThreadManageController::status' => '?',
            'App\\Controller\\ThreadManageController::upvote' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:deleteCategory' => '?',
            'App\\Controller\\AdminController:editCategory' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:newCategory' => '?',
            'App\\Controller\\AdminController:statistics' => '?',
            'App\\Controller\\ForumController:archived' => '?',
            'App\\Controller\\ForumController:deleteReply' => '?',
            'App\\Controller\\ForumController:detail' => '?',
            'App\\Controller\\ForumController:editReply' => '?',
            'App\\Controller\\ForumController:feed' => '?',
            'App\\Controller\\ForumController:followed' => '?',
            'App\\Controller\\ForumController:myThreads' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\NotificationController:delete' => '?',
            'App\\Controller\\NotificationController:index' => '?',
            'App\\Controller\\NotificationController:open' => '?',
            'App\\Controller\\NotificationController:seen' => '?',
            'App\\Controller\\NotificationController:seenAll' => '?',
            'App\\Controller\\NotificationController:widget' => '?',
            'App\\Controller\\ThreadManageController:delete' => '?',
            'App\\Controller\\ThreadManageController:downvote' => '?',
            'App\\Controller\\ThreadManageController:edit' => '?',
            'App\\Controller\\ThreadManageController:follow' => '?',
            'App\\Controller\\ThreadManageController:new' => '?',
            'App\\Controller\\ThreadManageController:pin' => '?',
            'App\\Controller\\ThreadManageController:status' => '?',
            'App\\Controller\\ThreadManageController:upvote' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.75u.tDw'])) {
            return $container->privates['.service_locator.75u.tDw'];
        }

        return $container->privates['.service_locator.75u.tDw'] = $instance;
    }
}
