<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MvDhjVEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MvDhjVE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'thread' => ['privates', '.errored..service_locator.MvDhjVE.App\\Entity\\ForumThread', NULL, 'Cannot autowire service ".service_locator.MvDhjVE": it needs an instance of "App\\Entity\\ForumThread" but this type has been excluded in "config/services.yaml".'],
            'threadService' => ['privates', 'App\\Service\\ThreadService', 'getThreadServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'thread' => 'App\\Entity\\ForumThread',
            'threadService' => 'App\\Service\\ThreadService',
        ]);

        if (isset($container->privates['.service_locator.MvDhjVE'])) {
            return $container->privates['.service_locator.MvDhjVE'];
        }

        return $container->privates['.service_locator.MvDhjVE'] = $instance;
    }
}
