<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IQcy2pBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iQcy2pB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notification' => ['privates', '.errored..service_locator.iQcy2pB.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.iQcy2pB": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'entityManager' => '?',
            'notification' => 'App\\Entity\\Notification',
        ]);

        if (isset($container->privates['.service_locator.iQcy2pB'])) {
            return $container->privates['.service_locator.iQcy2pB'];
        }

        return $container->privates['.service_locator.iQcy2pB'] = $instance;
    }
}
