<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G8PCkaGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G8PCkaG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G8PCkaG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'interactionRepository' => ['privates', 'App\\Repository\\PostInteractionRepository', 'getPostInteractionRepositoryService', true],
            'profileLookupService' => ['privates', 'App\\Service\\ProfileLookupService', 'getProfileLookupServiceService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'interactionRepository' => 'App\\Repository\\PostInteractionRepository',
            'profileLookupService' => 'App\\Service\\ProfileLookupService',
        ]);
    }
}
