<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H6O0oHAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H6O0oHA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'notification' => ['privates', '.errored..service_locator.H6O0oHA.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.H6O0oHA": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'notification' => 'App\\Entity\\Notification',
            'notificationService' => 'App\\Service\\NotificationService',
        ]);

        if (isset($container->privates['.service_locator.H6O0oHA'])) {
            return $container->privates['.service_locator.H6O0oHA'];
        }

        return $container->privates['.service_locator.H6O0oHA'] = $instance;
    }
}
