<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HdzICK7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HdzICK7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'reply' => ['privates', '.errored..service_locator.HdzICK7.App\\Entity\\Reply', NULL, 'Cannot autowire service ".service_locator.HdzICK7": it needs an instance of "App\\Entity\\Reply" but this type has been excluded in "config/services.yaml".'],
            'replyService' => ['privates', 'App\\Service\\ReplyService', 'getReplyServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'reply' => 'App\\Entity\\Reply',
            'replyService' => 'App\\Service\\ReplyService',
        ]);

        if (isset($container->privates['.service_locator.HdzICK7'])) {
            return $container->privates['.service_locator.HdzICK7'];
        }

        return $container->privates['.service_locator.HdzICK7'] = $instance;
    }
}
