<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInteractionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\InteractionService' shared autowired service.
     *
     * @return \App\Service\InteractionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'InteractionService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\InteractionService'])) {
            return $container->privates['App\\Service\\InteractionService'];
        }
        $b = ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService'));

        if (isset($container->privates['App\\Service\\InteractionService'])) {
            return $container->privates['App\\Service\\InteractionService'];
        }

        $instance = new \App\Service\InteractionService(($container->privates['App\\Repository\\PostInteractionRepository'] ?? $container->load('getPostInteractionRepositoryService')), $a, $b);

        if (isset($container->privates['App\\Service\\InteractionService'])) {
            return $container->privates['App\\Service\\InteractionService'];
        }

        return $container->privates['App\\Service\\InteractionService'] = $instance;
    }
}
