<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ModerationService' shared autowired service.
     *
     * @return \App\Service\ModerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ModerationService.php';

        return $container->privates['App\\Service\\ModerationService'] = new \App\Service\ModerationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
