<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ReplyService' shared autowired service.
     *
     * @return \App\Service\ReplyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReplyService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ReplyService'])) {
            return $container->privates['App\\Service\\ReplyService'];
        }
        $b = ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService'));

        if (isset($container->privates['App\\Service\\ReplyService'])) {
            return $container->privates['App\\Service\\ReplyService'];
        }

        $instance = new \App\Service\ReplyService($a, $b, ($container->privates['App\\Service\\ModerationService'] ?? $container->load('getModerationServiceService')));

        if (isset($container->privates['App\\Service\\ReplyService'])) {
            return $container->privates['App\\Service\\ReplyService'];
        }

        return $container->privates['App\\Service\\ReplyService'] = $instance;
    }
}
