<?php

namespace ContainerR6ehLaZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThreadServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ThreadService' shared autowired service.
     *
     * @return \App\Service\ThreadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ThreadService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ThreadService'])) {
            return $container->privates['App\\Service\\ThreadService'];
        }

        $instance = new \App\Service\ThreadService(($container->privates['App\\Repository\\ForumThreadRepository'] ?? $container->load('getForumThreadRepositoryService')), $a, ($container->privates['App\\Service\\ModerationService'] ?? $container->load('getModerationServiceService')));

        if (isset($container->privates['App\\Service\\ThreadService'])) {
            return $container->privates['App\\Service\\ThreadService'];
        }

        return $container->privates['App\\Service\\ThreadService'] = $instance;
    }
}
