security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            stateless: false
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\AccountStatusUserChecker
            entry_point: App\Security\ApiAwareEntryPoint
            custom_authenticators:
                - App\Security\Jwt\JwtAuthenticator

    access_control:
        # ===== AUTH PUBLIC =====
        - { path: ^/api/auth/2fa/check$, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/(login|register|logout|refresh|forgot-password|verify-reset-code|reset-password|reset/send|reset/confirm|verify-email|verify-email/resend|face/login|google/connect|google/callback)$, roles: PUBLIC_ACCESS }

        # ===== AUTH PROTECTED =====
        - { path: ^/api/auth/2fa/(enable|verify|disable)$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/auth/face/(enable|disable|enroll)$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/auth/me$, roles: IS_AUTHENTICATED_FULLY }

        # ===== FEATURES =====
        - { path: ^/api/avatar/generate$, roles: IS_AUTHENTICATED_FULLY }

        # ===== YOUR MODULES (SAFE ADD) =====
        - { path: ^/doctor, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/rdv, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/rapport, roles: IS_AUTHENTICATED_FULLY}

        # ===== EXISTING SYSTEM =====
        - { path: ^/(sommeil|reve), roles: [ROLE_PATIENT, ROLE_THERAPIST] }
        - { path: ^/user, roles: [ROLE_PATIENT, ROLE_THERAPIST] }
        - { path: ^/forum, roles: [ROLE_PATIENT, ROLE_THERAPIST] }
        - { path: ^/threads, roles: [ROLE_PATIENT, ROLE_THERAPIST] }
        - { path: ^/notifications, roles: [ROLE_PATIENT, ROLE_THERAPIST] }
        - { path: ^/api/user, roles: [ROLE_PATIENT, ROLE_THERAPIST] }

        # ===== ADMIN =====
        - { path: ^/admin/dashboard$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/admin, roles: ROLE_ADMIN }

        # ===== PUBLIC =====
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/doctors, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10