<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SokdwQVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SokdwQV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'notificationService' => 'App\\Service\\NotificationService',
        ]);

        if (isset($container->privates['.service_locator.SokdwQV'])) {
            return $container->privates['.service_locator.SokdwQV'];
        }

        return $container->privates['.service_locator.SokdwQV'] = $instance;
    }
}
