<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VBJCjPQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vBJCjPQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'interactionService' => ['privates', 'App\\Service\\InteractionService', 'getInteractionServiceService', true],
            'profileLookupService' => ['privates', 'App\\Service\\ProfileLookupService', 'getProfileLookupServiceService', true],
            'replyRepository' => ['privates', 'App\\Repository\\ReplyRepository', 'getReplyRepositoryService', true],
            'replyService' => ['privates', 'App\\Service\\ReplyService', 'getReplyServiceService', true],
            'summarizationService' => ['privates', 'App\\Service\\SummarizationService', 'getSummarizationServiceService', true],
            'thread' => ['privates', '.errored..service_locator.vBJCjPQ.App\\Entity\\ForumThread', NULL, 'Cannot autowire service ".service_locator.vBJCjPQ": it needs an instance of "App\\Entity\\ForumThread" but this type has been excluded in "config/services.yaml".'],
            'threadService' => ['privates', 'App\\Service\\ThreadService', 'getThreadServiceService', true],
            'translationService' => ['privates', 'App\\Service\\TranslationService', 'getTranslationServiceService', true],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'interactionService' => 'App\\Service\\InteractionService',
            'profileLookupService' => 'App\\Service\\ProfileLookupService',
            'replyRepository' => 'App\\Repository\\ReplyRepository',
            'replyService' => 'App\\Service\\ReplyService',
            'summarizationService' => 'App\\Service\\SummarizationService',
            'thread' => 'App\\Entity\\ForumThread',
            'threadService' => 'App\\Service\\ThreadService',
            'translationService' => 'App\\Service\\TranslationService',
        ]);

        if (isset($container->privates['.service_locator.vBJCjPQ'])) {
            return $container->privates['.service_locator.vBJCjPQ'];
        }

        return $container->privates['.service_locator.vBJCjPQ'] = $instance;
    }
}
