<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7vo_Mx5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7vo.mx5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'interactionService' => ['privates', 'App\\Service\\InteractionService', 'getInteractionServiceService', true],
            'thread' => ['privates', '.errored..service_locator.7vo.mx5.App\\Entity\\ForumThread', NULL, 'Cannot autowire service ".service_locator.7vo.mx5": it needs an instance of "App\\Entity\\ForumThread" but this type has been excluded in "config/services.yaml".'],
        ], [
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'interactionService' => 'App\\Service\\InteractionService',
            'thread' => 'App\\Entity\\ForumThread',
        ]);

        if (isset($container->privates['.service_locator.7vo.mx5'])) {
            return $container->privates['.service_locator.7vo.mx5'];
        }

        return $container->privates['.service_locator.7vo.mx5'] = $instance;
    }
}
