<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IY6bqSeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iY6bqSe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'currentUserService' => ['privates', 'App\\Service\\CurrentUserService', 'getCurrentUserServiceService', true],
            'profileLookupService' => ['privates', 'App\\Service\\ProfileLookupService', 'getProfileLookupServiceService', true],
            'threadService' => ['privates', 'App\\Service\\ThreadService', 'getThreadServiceService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'currentUserService' => 'App\\Service\\CurrentUserService',
            'profileLookupService' => 'App\\Service\\ProfileLookupService',
            'threadService' => 'App\\Service\\ThreadService',
        ]);

        if (isset($container->privates['.service_locator.iY6bqSe'])) {
            return $container->privates['.service_locator.iY6bqSe'];
        }

        return $container->privates['.service_locator.iY6bqSe'] = $instance;
    }
}
