<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForumThread3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vBJCjPQ.App\Entity\ForumThread' shared service.
     *
     * @return \App\Entity\ForumThread
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vBJCjPQ": it needs an instance of "App\\Entity\\ForumThread" but this type has been excluded in "config/services.yaml".');
    }
}
