<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\StatisticsService' shared autowired service.
     *
     * @return \App\Service\StatisticsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StatisticsService.php';

        return $container->privates['App\\Service\\StatisticsService'] = new \App\Service\StatisticsService(($container->privates['App\\Repository\\ForumThreadRepository'] ?? $container->load('getForumThreadRepositoryService')), ($container->privates['App\\Repository\\ReplyRepository'] ?? $container->load('getReplyRepositoryService')), ($container->privates['App\\Service\\ProfileLookupService'] ?? $container->load('getProfileLookupServiceService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Repository\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')));
    }
}
