<?php

namespace ContainerBOOwSEF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TranslationService' shared autowired service.
     *
     * @return \App\Service\TranslationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TranslationService.php';

        return $container->privates['App\\Service\\TranslationService'] = new \App\Service\TranslationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('string:API_TRANSLATE_KEY'));
    }
}
