parameters:
    app.upload_dir: '%kernel.project_dir%/public/uploads'
    app.translate_api_key: '%env(string:API_TRANSLATE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ImageUploadService:
        arguments:
            $uploadDir: '%app.upload_dir%'

    App\Service\TranslationService:
        arguments:
            $apiKey: '%app.translate_api_key%'
