parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'

    App\Service\ImageUploadService:
        arguments:
            $imageRequestUrl: '%env(string:IMAGE_REQUEST_URL)%'
            $imageApiKey: '%env(string:IMAGE_API_KEY)%'

    App\Service\WeatherService:
        arguments:
            $weatherApiKey: '%env(string:WEATHER_API_KEY)%'
            $city: '%env(string:WEATHER_CITY)%'